#!/usr/bin/expect -f
#!/bin/bash

set port	[lindex $argv 0];
set host	[lindex $argv 1];
set user	[lindex $argv 2];
set arg1	[lindex $argv 3];
set arg2	[lindex $argv 4];
set pass	[lindex $argv 5];
set timeout	10;
match_max	100000;

proc finish {} {
  set timeout -1;
  expect eof;
}

send_user "connecting to $host\n";
spawn ssh -NTp $port $user@$host -D 7070 -o "KeepAlive yes" -o "$arg1" -o "$arg2" -o "PermitLocalCommand yes" -o "LocalCommand echo 'proxyapp'";

expect {
	"*yes/no*"		{send "yes\r"; exp_continue};
	"*hostname*"	{puts "ERROR: INVALID SERVER"; exit};
	"*error*"		{puts "ERROR: CONNECTION ERROR"; exit};
	"*closed*"		{puts "ERROR: CONNECTION REFUSED"; exit};
	"*refused*"		{puts "ERROR: CONNECTION REFUSED"; exit};
	"*timed out*"	{puts "ERROR: CONNECTION TIMEOUT"; exit};
	"*bind*"		{puts "ERROR: BIND ALREADY IN USE"; exit};
	"*reset*"		{puts "ERROR: BLOCKED BY FIREWALL"; exit};
	"*proxyapp*"	{sleep 0; send_user "CONNECTED"; finish};
	"*?assword*"	{send "$pass\r"; expect {
		"*proxyapp*"	{sleep 0; send_user "CONNECTED"; finish};
		"*denied*"		{puts "ERROR: INVALID USERNAME OR PASSWORD"; exit};
	};}
}

send_user "ERROR: CONNECTION TIMEOUT";