#!/usr/bin/expect -f
#!/bin/sh

set port [lindex $argv 0]
set server [lindex $argv 1]
set user [lindex $argv 2]
set arg [lindex $argv 3]
set arg2 [lindex $argv 4]
set pass [lindex $argv 5]

send_user "connecting to $server\n"
spawn ssh -NTp $port $user@$server -D 7070 -o "KeepAlive yes" -o "$arg" -o "$arg2"

match_max 100000

set timeout 5
expect {
"?sh: Error*" {puts "CONNECTION ERROR"; exit};
"*yes/no*" {send "yes\r"; exp_continue};
"*Could not resolve hostname*" {puts "CONNECTION REFUSED"; exit};
"*Operation timed out*" {puts "CONNECTION REFUSED"; exit};
"*Connection refused*" {puts "CONNECTION REFUSED"; exit};
"*?assword:*" {	send "$pass\r"; set timeout 5;
expect "*?assword:*" {puts "\rWRONG PASSWORD"; exit;}
};
"*?ntering interactive session*" {send_user "CONNECTED"; set timeout -1; expect eof; exit;};
}

send_user "CONNECTED";
set timeout -1
expect eof;