#!/usr/bin/expect -f

set timeout -1

set port [lindex $argv 0]
set server [lindex $argv 1]
set user [lindex $argv 2]
set arg [lindex $argv 3]
set arg2 [lindex $argv 4]
set pass [lindex $argv 5]

send_user "connecting to $server\n"
spawn ssh -NTp $port $user@$server -D 7070 -o "KeepAlive yes" -o "$arg" -o "$arg2"

expect {
  "*?assword:*" { 
        send "$pass\n" 
        expect {
          "*>*" { }
          "*$*" { }
		  "*#*" { }
          "*~*" { }
          "*]*" { }
        }
  }
  default {
        send_user "Login failed\n"
        exit
  }
}